### PR TITLE
fix: clear delayed apps cache of migrations project state

### LINKED ISSUE #292: Models from app state aren't compatible (Cannot assign "<A: A object (1)>": "B.a_fk" must be a "A" instance)
I'm running into a problem when I apply a migration with `Migrator.apply_initial_migration()` and then try to construct model instances using the returned app state. One model has a foreign key to another model, but the foreign key field does not accept an instance of that model (see below for the exact output and exception).

I tried to reduce the setup as much a possible. In the end, two additional models and 2 indexes were necessary to trigger the issue. I tested it with django-test-migrations 1.2.0 and with Django 3.2.13 and 4.0.4. The attached ZIP archive contains a complete project which reproduces the issue:

[app-state-bug.zip](https://github.com/wemake-services/django-test-migrations/files/8787829/app-state-bug.zip)

To run the test, use the following couple of commands:

```
python3.10 -m venv venv
venv/bin/pip install django~=3.2 pytest-django django-test-migrations
venv/bin/pytest test_bad.py
```

When running this, you should see the following output:

```
___________________________________ test_bad ___________________________________

migrator = <django_test_migrations.migrator.Migrator object at 0x105c44430>

    def test_bad(migrator):
        state = migrator.apply_initial_migration(('my_app', '0002_foo'))
    
        A = state.apps.get_model('my_app', 'A')
        B = state.apps.get_model('my_app', 'B')
    
        print(id(A), id(B.a_fk.field.related_model))
    
>       B.objects.create(a_fk=A.objects.create(foo=1))

test_bad.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.10/site-packages/django/db/models/manager.py:85: in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
venv/lib/python3.10/site-packages/django/db/models/query.py:512: in create
    obj = self.model(**kwargs)
venv/lib/python3.10/site-packages/django/db/models/base.py:541: in __init__
    _setattr(self, field.name, rel_obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x105c47520>
instance = <B: B object (None)>, value = <A: A object (1)>

    def __set__(self, instance, value):
        """
        Set the related instance through the forward relation.
    
        With the example above, when setting ``child.parent = parent``:
    
        - ``self`` is the descriptor managing the ``parent`` attribute
        - ``instance`` is the ``child`` instance
        - ``value`` is the ``parent`` instance on the right of the equal sign
        """
        # An object must be an instance of the related class.
        if value is not None and not isinstance(
            value, self.field.remote_field.model._meta.concrete_model
        ):
>           raise ValueError(
                'Cannot assign "%r": "%s.%s" must be a "%s" instance.'
                % (
                    value,
                    instance._meta.object_name,
                    self.field.name,
                    self.field.remote_field.model._meta.object_name,
                )
E               ValueError: Cannot assign "<A: A object (1)>": "B.a_fk" must be a "A" instance.

venv/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py:235: ValueError
```

### PR DESCRIPTION
**Pull request by skarzi**
I am still thinking about the test (how to write the simplest and minimal version of it), so this PR is a draft, but feel free to write some suggestions in the comments.

Closes #292

### CODE REVIEW

**Comment by sobolevn** [comment]
Will https://github.com/wemake-services/django-test-migrations/files/8787829/app-state-bug.zip help?

**Comment by jrobichaud** [comment]
This fixes a problem I am having. I have the same symptom as #292

I copy my factory_boy's factories in my migration testcase to instantiate my models.

```python
    def prepare(self):
        User = self.old_state.apps.get_model("accounts", "User")

        class UserFactory(DjangoModelFactory):
            first_name = factory.Faker("first_name")
            last_name = factory.Faker("last_name")
            email = factory.Sequence(lambda n: "user-{}@example.com".format(n))

            class Meta:
                model = User
```

We have very complex and deep factories.

`factory_boy`'s `factory.RelatedFactory` are having erratic behaviours in the migration tests. Internally it might be using the forward keys like in #292.

**Comment by sobolevn** [comment]
@jrobichaud hey, thanks for the heads up! We can try this:
- I can merge it 
- You can try the latest version from git
- Report back how does it behave

Does this sound fine? :)

**Review by sobolevn — APPROVED** [review]

**Comment by jrobichaud** [comment]
I tested it this way already using version `1.3.0`:

```
from django_test_migrations.contrib.unittest_case import MigratorTestCase
from django_test_migrations.migrator import Migrator
from django_test_migrations.signals import mute_migrate_signals


class CustomMigrator(Migrator):
    def _migrate(
        self,
        migration_targets,
        plan=None,
    ):
        """_migrate as of #294"""
        with mute_migrate_signals():
            project_state = self._executor.migrate(migration_targets, plan=plan)
            project_state.clear_delayed_apps_cache()
            return project_state


class CustomMigratorTestCase(MigratorTestCase):
    def setUp(self):
        """
        Same as the original setUp method, but uses CustomMigrator instead of Migrator
        :return:
        """
        self._migrator = CustomMigrator(self.database_name)
        self.old_state = self._migrator.apply_initial_migration(
            self.migrate_from,
        )
        self.prepare()
        self.new_state = self._migrator.apply_tested_migration(self.migrate_to)
```

All my 10 migration tests work.

**Comment by jrobichaud** [comment]
You can merge it and even create a new release for it. 

I am confident what I did with my Custom classes is legit to validate the fix.

I do not think I need to test it again in `master` but I can if you think it is useful.

**Comment by jrobichaud** [comment]
Are you planning to create a new release with this or I should use the latest master commit for a while?

**Comment by sobolevn** [comment]
Working on it :)

**Pull request merged**
