### PR TITLE
fix AnyConnection type for django > 3.1

### PR DESCRIPTION
**Pull request by skarzi**

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks!

What else is required before the release?

**Comment by skarzi** [comment]
> What else is required before the release?

I think only some more tests on real-life projects. So far, I had tested `master` branch with several projects, but only with `django > 3.0`.
Let's wait until Monday with the release, so I can check `django-test-migrations` on more projects

**Comment by skarzi** [comment]
@sobolevn I have tested `django-test-migration` on few quite big projects (django==1.11 and django==3.1, both with PostgreSQL DB), and everything worked like before so I guess now, we can release a new version and wait for feedback from others

**Comment by sobolevn** [comment]
Awesome! Thank you!

**Pull request merged**
