### PR TITLE
add Makefile and minor fixes

### PR DESCRIPTION
**Pull request by skarzi**

### CODE REVIEW

**Comment by sobolevn** [comment]
Thanks 👍

**Comment by skarzi** [comment]
Should I merge, squash or rebase this PR?
What merging strategy do you prefer to use in this project?

**Comment by sobolevn** [comment]
I usually use "Squash". And you?

**Comment by skarzi** [comment]
OK, thanks for merging ;)
It depends on the case, but for such small PRs I also prefer squash

**Pull request merged**
