### PR TITLE
version 1.1.0 release

### PR DESCRIPTION
**Pull request by skarzi**

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
@skarzi thanks a lot! Do you have PyPI access for this repo?

**Comment by skarzi** [comment]
> @skarzi thanks a lot! Do you have PyPI access for this repo?

Yes, should I publish the new version to PyPI?

**Comment by sobolevn** [comment]
@skarzi yes, please! 🙏 

Happy New Year and Xmas! 🎄 
Thanks a lot for all your help in 2020 🙂

**Comment by skarzi** [comment]
So I'm merging this PR and doing a release :+1: 

Thank you! It's a pleasure to work with you!

Merry Christmas and happy new year! :santa:

**Comment by skarzi** [comment]
version 1.1.0 is available on PyPI :tada:

**Pull request merged**
